### ISSUE TITLE
Tiny Vue based on Vue 2.x

### ISSUE THREAD

**Issue by miljan-aleksic** [lihongxun945/tiny-vue#1]
Hi, this project is very interesting for learning about Vue internals, is there any plan to update to Vue 2.x?

**Comment by lihongxun945** [comment]
@miljan-aleksic Thanks, I am just starting reading Vue2.x source code. No plan to update to Vue2 right now.
But maybe, next year.

**Comment by miljan-aleksic** [comment]
Better than nothing :) Thanks and keep up the good work.
